### ISSUE TITLE
Add time and publication information ？

### ISSUE THREAD

**Issue by zhangyixing3** [colindaven/awesome-pangenomes#8]
Dear sir, I want to add time and publication information for each type of software, and each tool will be sorted chronologically.

**Comment by zhangyixing3** [comment]
What do you think?

**Comment by colindaven** [comment]
Publication information should be included in the github repos of the various projects. That would be a lot of work I think and not the primary goal of this repository, so it would be a "nice to have" from my point of view rather than essential.

Time is important, I agree, but which time ? Publication date? Old projects might be the most established and useful  though ? Date since last github changes - this is impossible to maintain.

Perhaps what matters more is popularity, eg github stars, but this is also always out of date. Maybe we can just mark very popular projects with an icon ? Eg vg, odgi, minigraph, etc ?

What do you think ?

**Comment by zhangyixing3** [comment]
Thanks for your quickly response.
> Publication information should be included in the github repos of the various projects. That would be a lot of work I think and not the primary goal of this repository, so it would be a "nice to have" from my point of view rather than essential.

I fully agree. Perhaps I'm seeing it from a somewhat limited perspective. Sorry for this.
> Time is important, I agree, but which time ? Publication date? Old projects might be the most established and useful though ? Date since last github changes - this is impossible to maintain.
> Perhaps what matters more is popularity, eg github stars, but this is also always out of date. Maybe we can just mark very popular projects with an icon ? Eg vg, odgi, minigraph, etc ?

Some older tools are indeed very useful. Personally, I feel that newer tools (those with more recent publication dates) are likely to perform better than older ones. I fully support marking very popular projects with an icon.

**Comment by colindaven** [comment]
I added :rocket: to my purely subjective impression of important and popular repos. Maybe you have other impressions as well ?

**Comment by zhangyixing3** [comment]
Sorry for the late reply.  Great job!
